import ad2 from '../../public/assets/ad2.png'
import Picture10 from '../../public/assets/Picture10.png';

const advertisementContent = {
    en: [
        {
            title: 'Zirconium Crowns',
            description: 'Package',
            image: Picture10,
            firstlink: 'Zirconium crowns up to 24 teeth',
            secondlink: 'Panoramic x-ray',
            thirdlink: 'Digital smile design',
            fourthlink: 'Non surgical procedure such as tooth extraction, filling, root canal, gingivectomy treatments',
            fifthlink: 'Flight Ticket',
            sixthlink: 'Translation support',
            seventhlink: 'Home medications',
            eighthlink: ' Transportation with private car and translator, 2 ways from and to airport, from hotel to clinic and vice versa',
            ninethlink: ' 5-Star hotel accommodation 7 nights (8 Days) including breakfast with 1 companion',
            tenthlink: 'City tour with private car',
            eleventhlink: 'Follow-up with doctor for 2 years after treatment',
            twelvethlink: '5 years of warranty',
            discount: '30%',
            save: 'Save'
        },
        {
            id: 2,
            title: 'E-Max Laminate Veneers or Crowns',
            description: 'Package',
            image: ad2,
            firstlink: 'E-Max Laminate veneers or crowns up to 24 teeth',
            secondlink: 'Panoramic x-ray',
            thirdlink: 'Digital smile design',
            fourthlink: 'Non surgical procedure such as tooth extraction, filling, root canal, gingivectomy treatments',
            fifthlink: 'Flight Ticket',
            sixthlink: 'Translation support',
            seventhlink: 'Home medications',
            eighthlink: ' Transportation with private car and translator, 2 ways from and to airport, from hotel to clinic and vice versa',
            ninethlink: ' 5-Star hotel accommodation 7 nights (8 Days) including breakfast with 1 companion',
            tenthlink: 'City tour with private car',
            eleventhlink: 'Follow-up with doctor for 2 years After treatment',
            twelvethlink: '5 years of warranty',
            discount: '35%',
            save: 'Save'
        },
    ],

    tr: [
        {
            id: 1,
            title: 'Zirkonyum Kaplama',
            description: 'Paketi',
            image: Picture10,
            firstlink: '24 Dişe kadar Zirkonyum Kuron',
            secondlink: 'Panoramik Röntgen',
            thirdlink: 'Dijital gülüş tasarımı',
            fourthlink: 'Diş çekimi, dolgu, kanal tedavisi, diş eti tedavileri gibi cerrahi olmayan işlemler',
            fifthlink: 'Uçuş Bileti',
            sixthlink: 'Çeviri desteği',
            seventhlink: 'Tedavi Sonrası İlaç Desteği',
            eighthlink: 'Ulaşım Desteği (Tedavi süresince özel araç ve tercüman ile)',
            ninethlink: '5 yıldızlı otelde 7 gece (8 Gün) 1 refakatçi ile kahvaltı dahil konaklama',
            tenthlink: 'Özel araçla şehir turu',
            eleventhlink: 'Tedaviden 1 yıl sonra doktor takibi',
            twelvethlink: '5 yıl garanti',  
            discount: '30%',
            save: 'Tasarruf Et'
        },
        {
            id: 2,
            title: 'E-Max Lamina Veneer veya Kuron',
            description: 'Paketi',
            image: ad2,
            firstlink: '24 dişe kadar E-Max Lamina Veneer veya Kuron',
            secondlink: 'Panoramik Röntgen',
            thirdlink: 'Dijital gülüş tasarımı',
            fourthlink: 'Diş çekimi, dolgu, kanal tedavisi, diş eti tedavileri gibi cerrahi olmayan işlemler',
            fifthlink: 'Uçak bileti',
            sixthlink: 'Çeviri desteği',
            fifthlink: 'Uçuş Bileti',
            sixthlink: 'Çeviri desteği',
            seventhlink: 'Tedavi Sonrası İlaç Desteği',
            eighthlink: 'Ulaşım Desteği (Tedavi süresince özel araç ve tercüman ile)',
            ninethlink: '5 yıldızlı otelde 7 gece (8 Gün) 1 refakatçi ile kahvaltı dahil konaklama',
            tenthlink: 'Özel araçla şehir turu',
            eleventhlink: 'Tedaviden 1 yıl sonra doktor takibi',
            twelvethlink: '5 yıl garanti',  
            discount: '35%',
            save: 'Tasarruf Et'
        },
    ],

    fr: [
        {
            id: 1,
            title: 'Couronnes en zircone',  
            description: 'Forfait',
            image: Picture10,
            firstlink: 'Couronnes en zircone jusqu\'à 24 dents',
            secondlink: 'Radiographie panoramique',
            thirdlink: 'Conception numérique du sourire',
            fourthlink: 'Procédure non chirurgicale telle que l extraction dentaire, l obturation, le traitement de canal, la gingivectomie',
            fifthlink: 'Billet davion',
            sixthlink: 'Aide à la traduction',
            seventhlink: 'Médicaments à domicile',
            eighthlink: 'Transport avec voiture privée et traducteur, 2 voies de et vers laéroport, de lhôtel à la clinique et vice versa',
            ninethlink: 'Hébergement dans un hôtel 5 étoiles pour 7 nuits (8 jours), petit-déjeuner compris, avec 1 accompagnateur',
            tenthlink: 'Visite de la ville avec voiture privée',
            eleventhlink: 'Suivi par un médecin pendant 2 ans après le traitement',
            twelvethlink: '5 ans de garantie',
            discount: '30%',  
            save: 'Economiser'
        },
        {
            id: 2,
            title: 'Facettes ou couronnes en stratifié E-Max',
            description: 'Forfait',
            image: ad2,
            firstlink: 'Facettes ou couronnes en E-Max jusqu\'à 24 dents',
            secondlink: 'Radiographie panoramique',
            thirdlink: 'Conception numérique du sourire',
            fourthlink: 'Procédure non chirurgicale telle que lextraction dentaire, lobturation, le traitement de canal, les traitements de gingivectomie',
            fifthlink: 'Billet davion',
            sixthlink: 'Aide à la traduction',
            seventhlink: 'Médicaments à domicile',
            eighthlink: 'Transport avec voiture privée et traducteur, 2 voies de et vers laéroport, de lhôtel à la clinique et vice versa',
            ninethlink: 'Hébergement dans un hôtel 5 étoiles pour 7 nuits (8 jours), petit-déjeuner compris, avec 1 accompagnateur',
            tenthlink: 'Visite de la ville avec voiture privée',
            eleventhlink: 'Suivi par un médecin pendant 2 ans après le traitement',
            twelvethlink: '5 ans de garantie',
            discount: '35%',  
            save: 'Economiser'
        },
    ],
}

export default advertisementContent;
