import girldoctor from '../../public/assets/girldoctor.png'
import oldmandoctor from '../../public/assets/oldmandoctor.png'
import womandoctor from '../../public/assets/womandoctor.png'
import younggirldoctor from '../../public/assets/younggirldoctor.png'
import girldoctorwithblackhair from '../../public/assets/girldoctorwithblackhair.png'
import wp from '../../public/assets/wp.png';
import wptr from '../../public/assets/wptr.png';
import wpfr from '../../public/assets/wpfr.png';

const doctors = {
    en: [
        {
            title: 'Our Specialist Doctors',
            name: 'Dr. Ghazwan Ghazi',
            treatment: '',
            way: 'Periodontist & Dental Implant Specialist',
            education: 'Boston University School of Dentistry- Bachelor Degree1992 New Jersey Dental School- Masters Degree 1997 Harvard School of Dental Medicine: Lecturer on Oral Medicine, Infection and Immunity',   
            image: oldmandoctor,
            language: 'English, Arabic, French',
            speciality: 'Dental Implant, All-On-4/6, Bone Grafting, Sinus Lifting, Gum Disease Treatment, Gingivitis Treatment, Aesthetic Gum Treatment, Gingival Recession, Bleeding Gum',
            years: '15 years',
            wp: wp,
            first: "Specialty:",
            second: "Education:",
            third: "Languages:",
            forth: "Experience:",
            wp: "https://api.whatsapp.com/send?phone=905308309219",

        },
        {
            title: 'Our Specialist Doctors',
            name: 'Dr. Ebru Bütün',
            way: 'Periodontist & Dental Implant Specialist',  
            education: "Ankara University – Faculty of Dentistry - Dentistry 2007 _2012 Bolu Abant İzzet Baysal University – Faculty of Dentistry - Periodontology 2017_ 2021 " ,
            image: girldoctor,
            language: 'English,Turkish',
            speciality:  'Dental Implant, All-On-4/6, Bone Grafting, Sinus Lifting, Gum Disease Treatment, Gingivitis Treatment, Aesthetic Gum Treatment, Gingival Recession, Bleeding Gum' ,
            years: '10 years',
            wp: wp,
            first: "Specialty:",
            second: "Education:",
            third: "Languages:",
            forth: "Experience:",
            wp: "https://api.whatsapp.com/send?phone=905308309219",
        },
        {
            title: 'Our Specialist Doctors',
          name: 'Dr. Melek Aksoy',
          way: 'Cosmetic Specialist',   
          education: "Biruni university of dentistry 2015 _ 2020 ", 
          image: younggirldoctor,
          language: 'English, Arabic, Turkish',
          speciality:  'Smile Design (Zirconium Crowns, E-Max Laminate Veneers), Composite Bonding, Inlay & Onlay, Teeth Whitening / Bleaching' ,
          years: '5 years',
          wp: wp,
          first: "Specialty:",
          second: "Education:",
          third: "Languages:",
          forth: "Experience:",
          wp: "https://api.whatsapp.com/send?phone=905308309219",
        },
    ],

    tr: [
        {
            title: 'Uzman Doktorlarımız',
            name: 'Dr. Ghazwan Ghazi',
            treatment: '',
            way: 'Periodontist & İmplantoloji Uzmanı',
            education: 'Boston Üniversitesi Diş Hekimliği Fakültesi- Lisans Derecesi1992 New Jersey Dental School- Yüksek Lisans Derecesi 1997 Harvard Diş Hekimliği Okulu: Ağız Hastalıkları, Enfeksiyon ve Bağışıklık Konusunda Öğretim Görevlisi',
            image: oldmandoctor,
            language: 'İngilizce, Arapça, Fransızca',
            speciality: 'Dental İmplant, All-On-4/6, Kemik Grefti, Sinus Kaldırma, Diş Eti Hastalıkları Tedavisi, Gingivitis Tedavisi, Estetik Diş Eti Tedavisi, Gingival Recession, Bleeding Gum',
            years: '15 Yıl',
            wp: wptr,
            first: "Uzmanlık Alanı:",
            second: "Eğitim:",
            third: "Diller:",
            forth: "Deneyim:",
            wp:  "https://api.whatsapp.com/send?phone=905398289219"
        },
        {
            title: 'Uzman Doktorlarımız',
            name: 'Dr. Ebru Bütün',
            way: 'Periodontist & İmplantoloji Uzmanı',
            education: "Ankara Üniversitesi Diş Hekimliği Fakültesi - Diş Hekimliği 2007 _2012 Bolu Abant İzzet Baysal Üniversitesi Diş Hekimliği Fakültesi - Periodontoloji 2017_ 2021 ",
            image: girldoctor,
            language: 'İngilizce, Türkçe',
            speciality: 'Dental İmplant, All-On-4/6, Kemik Grefti, Sinus Kaldırma, Diş Eti Hastalıkları Tedavisi, Gingivitis Tedavisi, Estetik Diş Eti Tedavisi, Gingival Recession, Bleeding Gum',
            years: '10 Yıl',
            wp: wptr,
            first: "Uzmanlık Alanı:",
            second: "Eğitim:",
            third: "Diller:",
            forth: "Deneyim:",
            wp:  "https://api.whatsapp.com/send?phone=905398289219",
        },
        {
            title: 'Uzman Doktorlarımız',
            name: 'Dr. Melek Aksoy',
            way: 'Estetik Diş Hekimi',
            education: "Biruni Üniversitesi Diş Hekimliği 2015 _2020 ",
            image: younggirldoctor,
            language: 'İngilizce, Arapça, Türkçe',
            speciality: `Gülüş Tasarımı (Zirkonyum Porselen Kaplama,
                 E-Max Laminate Veneers), Kompozit Bonding, İnley & Onley, Diş Beyazlatma / Bleaching`,
            years: '5 Yıl',
            wp: wptr,
            first: "Uzmanlık Alanı:",
            second: "Eğitim:",
            third: "Diller:",
            forth: "Deneyim:",
            wp:  "https://api.whatsapp.com/send?phone=905398289219",
        },
    ],

    fr: [
        {
            title: 'Nos médecins spécialistes',
            name: 'Dr. Ghazwan Ghazi',
            treatment: '',
            way: 'Parodontiste et spécialiste des implants dentaires',
            education: "École dentaire de luniversité de Boston - Licence 1992 École dentaire du New Jersey - Maîtrise 1997 École de médecine dentaire de Harvard : Chargé de cours sur la médecine bucco-dentaire, les infections et l'immunité",
            image: oldmandoctor,
            language: ' Anglais, Arabe, Français',
            speciality: ' Implants dentaires, All-On-4/6, greffe osseuse, élévation des sinus, Traitement des maladies des gencives, traitement esthétique des gencives, traitement de la gingivite, récession gingivale, saignement des gencives.',
            years: '15 ans',
            wp: wpfr,
            first: "Spécialité:",
            second: "Formation:",
            third: "Langues:",
            forth: "Expérience:",
            wp: "https://api.whatsapp.com/send?phone=905308309219",
        },
        {
            title: 'Nos médecins spécialistes',
            name: 'Dr. Ebru Bütün',
            way: 'Parodontiste et spécialiste des implants dentaires',
            education: "Faculté de médecine dentaire de l'université d'Ankara - Dentisterie 2007 _2012 Faculté de médecine dentaire de l'université Bolu Abant İzzet Baysal - Parodontologie 2017_ 2021 ",
            image: girldoctor,
            language: 'Anglais, Turc',
            speciality: 'Implant dentaire, All-On-4/6, greffe osseuse, élévation des sinus,Traitement des maladies des gencives, traitement de la gingivite, traitement esthétique des gencives, récession gingivale, saignement des gencives.',
            years: '10  ans',
            wp: wpfr,
            first: "Spécialité:",
            second: "Formation:",
            third: "Langues:",
            forth: "Expérience:",
            wp: "https://api.whatsapp.com/send?phone=905308309219",
        },
        {
            title: 'Nos médecins spécialistes',
            name: 'Dr. Melek Aksoy',
            way: 'Spécialiste de lesthétique',
            education: "Faculté de médecine dentaire de l'université de Biruni 2015 _2020 ",
            image: younggirldoctor,
            language: 'Anglais, Arabe, Turc',
            speciality: 'Conception de Sourire (Couronnes en Zircone, Facettes en E-Max), Collage Composite, Inlay & Onlay, Blanchiment des Dents / Blanchiment',
            years: '5  ans',
            wp: wpfr,
            first: "Spécialité:",
            second: "Formation:",
            third: "Langues:",
            forth: "Expérience:",
            wp: "https://api.whatsapp.com/send?phone=905308309219",
        },
    ],
}

export default doctors;