const partnerContent = {
    en: {
        title: 'OUR PARTNERS IN USA',
        first: 'OUR SOLUTION PARTNERS',
        second: 'Best Patient Experience',
        third:'We Speak Multiple Languages',
        line1: 'We pride ourselves on the best',
        line2: 'quality customer services in',
        line3: 'Turkey and Europe backed by',
        line4: 'decades of clinical experience.',
        line5: 'Our belief is that healthy mouths',
        line6: 'always lead to healthy bodies.',
        l1: 'Our doctors and medical team speak',
        l2: 'multiple languages where they can',
        l3: 'communicate directly with our',
        l4: 'patients to make sure all their',
        l5: 'dental needs are met.',

        formtitle: 'Get a Free Quote',
        formname: 'Full Name',
        fillname: 'Please enter your name',
        formemail: 'Email',
        fillemail: 'Please enter your email',
        formphone: 'Phone Number',
        submit : 'Submit Now',
        faceLink: "https://www.facebook.com/Qualidentclinic",
        instaLink: " https://instagram.com/qualidentinternational?igshid=MzRlODBiNWFlZA",
        whatsLink: "https://api.whatsapp.com/send?phone=905308309219"
    },

    tr: {
        title: "ABD'DEKİ ORTAKLARIMIZ",
        first: 'ÇÖZÜM ORTAKLARIMIZ',
        second: 'En İyi Hasta Deneyimi',
        third:'Birden Fazla Dil Konuşuyoruz',
        line1: "Türkiye ve Avrupa'da onlarca ",
        line2: 'yıllık klinik deneyimine dayanarak',
        line3: 'en iyi hasta hizmetleri sunmaktan',
        line4: 'gurur duymaktayız. Inanıyoruz ki sağlıklı',
        line5: 'ağız her zaman sağlıklı vücuda yol açmaktadır.',
        l1: 'Hastalarımıza en kaliteli hizmet ve tedavi ',
        l2: ' sunabilmek ve tüm diş ihtiyaçlarının ',
        l3: ' karşılandığından emin olmak için birden ',
        l4: ' fazla dil konuşan doktorlarımız ve medikal  ',
        l5: 'ekibimiz tüm tedavi süresince yanınızda olacaktır.',

        formtitle: 'Ücretsiz Fiyat Teklifi Alın',
        formname: 'Ad Soyad',
        fillname: 'Lütfen adınızı giriniz',
        formemail: 'Email',
        fillemail: 'Lütfen email adresinizi giriniz',
        formphone: 'Telefon Numarası',
        submit : 'Şimdi Gönder',
        faceLink: "https://www.facebook.com/Qualident.tr?mibextid=LQQJ4d",
        instaLink: "https://www.instagram.com/qualident.clinic/?igshid=MzRlODBiNWFlZA",
        whatsLink: "https://api.whatsapp.com/send?phone=905398289219"
    },

    fr: {
        title: 'NOS PARTENAIRES AUX ÉTATS-UNIS',
        first: 'NOS PARTENAIRES DE SOLUTION',
        second: 'Meilleure expérience patient',
        third:'Nous parlons plusieurs langues',
        line1: 'Nous sommes fiers d offrir des services',
        line2: 'à la clientèle de la meilleure qualité en',
        line3: 'Turquie et en Europe, qui s appuient',
        line4: 'sur des décennies d expérience',
        line5: 'clinique. Notre conviction est qu une',
        line6: 'bouche saine mène toujours à un corps sain.',

        l1: 'Nos médecins et notre équipe médicale parlent plusieurs',
        l2: 'langues et peuvent ainsi communiquer',
        l3: 'directement avec nos avec nos patients pour',
        l4: "s'assurer que tous leurs besoins",
        l5: 'dentaires sont satisfaits.',

        formtitle: 'Obtenez un devis gratuit',
        formname: 'Nom complet',
        fillname: 'Veuillez entrer votre nom',
        formemail: 'Email',
        fillemail: 'Veuillez entrer votre email',
        formphone: 'Numéro de téléphone',
        submit : 'Envoyer maintenant',
        faceLink: "https://www.facebook.com/Qualidentclinic?mibextid=LQQJ4d",
        instaLink: " https://instagram.com/qualidentinternational?igshid=MzRlODBiNWFlZA",
        whatsLink: "https://api.whatsapp.com/send?phone=905308309219"
    },
}

export default partnerContent;