const valueContent = {
    en: {
        title: 'Value Added Benefits',
        first: 'Priority Appointments',
        second: 'Transportation',
        third: 'Accommodation',
        fourth: 'Teleconsultation',
        fifth: '24/7 Patient Support',
        sixth: 'Digital smile design',
        seventh: 'Travel Insurance',
        eighth: 'Translation Support',
        ninth: 'City Tour',
        tenth: 'Home Medications',
        eleventh: 'Cancel Anytime with full Refund',
        twelfth: 'Follow-up after treatment',
    },

    tr: {
        title: 'Katma Değerli Hizmetleri',
        first: 'Öncelikli Randevu',
        second: 'Ulaşım',
        third: 'Konaklama',
        fourth: 'Telekonsültasyon',
        fifth: '7/24 Hasta Desteği',
        sixth: 'Dijital Gülüş Tasarımı',
        seventh: 'Seyahat Sigortası',
        eighth: 'Çeviri Desteği',
        ninth: 'Şehir Turu',
        tenth: 'Tedavi Sonrası İlaç Desteği',
        eleventh: 'Tedavi İptal Durumunda Tam Para İadesi',
        twelfth: 'Tedavi sonrası Doktor Takibi',
    },

    fr: {
        title: 'Avantages à Valeur Ajoutée',
        first: 'Rendez-vous prioritaires',
        second: 'Transport',
        third: 'Hébergement',
        fourth: 'Téléconsultation',
        fifth: 'Assistance aux patients 24/7',
        sixth: 'Dessin numérique du sourire',
        seventh: 'Assurance voyage',
        eighth: 'Aide à la traduction',
        ninth: 'Visite de la ville',
        tenth: 'Médicaments à domicile',
        eleventh: 'Annulation à tout moment avec remboursement intégral ',
        twelfth: 'Suivi après le traitement',
    },
}

export default valueContent
